import numpy as np
from qiskit import QuantumCircuit
from qiskit import QuantumRegister
qr = QuantumRegister(7)
qcAdd = QuantumCircuit(qr)

qcAdd.h(qr[3])
qcAdd.barrier(qr)
qcAdd.p(np.pi/4, qr[3])
qcAdd.barrier(qr)
qcAdd.cx(qr[4], qr[3])
qcAdd.barrier(qr)
qcAdd.p(-np.pi/4, qr[3])
qcAdd.barrier(qr) 
qcAdd.cx(qr[4], qr[3])
qcAdd.barrier(qr)
qcAdd.p(np.pi/8, qr[3])
qcAdd.barrier(qr)
qcAdd.cx(qr[5], qr[3])
qcAdd.barrier(qr)
qcAdd.p(-np.pi/8, qr[3])
qcAdd.barrier(qr)
qcAdd.cx(qr[5], qr[3])
qcAdd.barrier(qr)
qcAdd.p(0.19634954084936207, qr[3])
qcAdd.barrier(qr)
qcAdd.cx(qr[6], qr[3])
qcAdd.barrier(qr)
qcAdd.p(-0.19634954084936207, qr[3])
qcAdd.barrier(qr)
qcAdd.cx(qr[6], qr[3])
qcAdd.barrier(qr)
qcAdd.h(qr[4])
qcAdd.barrier(qr)
qcAdd.p(np.pi/4, qr[4])
qcAdd.barrier(qr)
qcAdd.cx(qr[5], qr[4])
qcAdd.barrier(qr)
qcAdd.p(-np.pi/4, qr[4])
qcAdd.barrier(qr)
qcAdd.cx(qr[5], qr[4])
qcAdd.barrier(qr)
qcAdd.p(np.pi/8, qr[4])
qcAdd.barrier(qr)
qcAdd.cx(qr[6], qr[4])
qcAdd.barrier(qr)
qcAdd.p(-np.pi/8, qr[4])
qcAdd.barrier(qr)
qcAdd.cx(qr[6], qr[4])
qcAdd.barrier(qr)
qcAdd.h(qr[5])
qcAdd.barrier(qr)
qcAdd.p(np.pi/4, qr[5])
qcAdd.barrier(qr)
qcAdd.cx(qr[6], qr[5])
qcAdd.barrier(qr)
qcAdd.p(-np.pi/4, qr[5])
qcAdd.barrier(qr)
qcAdd.cx(qr[6], qr[5])
qcAdd.barrier(qr)
qcAdd.h(qr[6])
qcAdd.barrier(qr)
qcAdd.p(np.pi/2, qr[3])
qcAdd.barrier(qr)
qcAdd.cx(qr[0], qr[3])
qcAdd.barrier(qr)
qcAdd.p(-np.pi/2, qr[3])
qcAdd.barrier(qr)
qcAdd.cx(qr[0], qr[3])
qcAdd.barrier(qr)
qcAdd.p(np.pi/4, qr[3])
qcAdd.barrier(qr)
qcAdd.cx(qr[1], qr[3])
qcAdd.barrier(qr)
qcAdd.p(-np.pi/4, qr[3])
qcAdd.barrier(qr)
qcAdd.cx(qr[1], qr[3])
qcAdd.barrier(qr)
qcAdd.p(np.pi/8, qr[3])
qcAdd.barrier(qr)
qcAdd.cx(qr[2], qr[3])
qcAdd.barrier(qr)
qcAdd.p(-np.pi/8, qr[3])
qcAdd.barrier(qr)
qcAdd.cx(qr[2], qr[3])
qcAdd.barrier(qr)
qcAdd.p(np.pi/2, qr[4])
qcAdd.barrier(qr)
qcAdd.cx(qr[1], qr[4])
qcAdd.barrier(qr)
qcAdd.p(-np.pi/2, qr[4])
qcAdd.barrier(qr)
qcAdd.cx(qr[1], qr[4])
qcAdd.barrier(qr)
qcAdd.p(np.pi/4, qr[4])
qcAdd.barrier(qr)
qcAdd.cx(qr[2], qr[4])
qcAdd.barrier(qr)
qcAdd.p(-np.pi/4, qr[4])
qcAdd.barrier(qr)
qcAdd.cx(qr[2], qr[4])
qcAdd.barrier(qr)
qcAdd.p(np.pi/2, qr[5])
qcAdd.barrier(qr)
qcAdd.cx(qr[2], qr[5])
qcAdd.barrier(qr)
qcAdd.p(-np.pi/2, qr[5])
qcAdd.barrier(qr)
qcAdd.cx(qr[2], qr[5])
qcAdd.barrier(qr)
qcAdd.h(qr[6])
qcAdd.barrier(qr)
qcAdd.p(np.pi/4, qr[5])
qcAdd.barrier(qr)
qcAdd.cx(qr[6], qr[5])
qcAdd.barrier(qr)
qcAdd.p(-np.pi/4, qr[5])
qcAdd.barrier(qr)
qcAdd.cx(qr[6], qr[5])
qcAdd.barrier(qr)
qcAdd.h(qr[5])
qcAdd.barrier(qr)
qcAdd.p(np.pi/4, qr[4])
qcAdd.barrier(qr)
qcAdd.cx(qr[5], qr[4])
qcAdd.barrier(qr)
qcAdd.p(-np.pi/4, qr[4])
qcAdd.barrier(qr)
qcAdd.cx(qr[5], qr[4])
qcAdd.barrier(qr)
qcAdd.p(np.pi/8, qr[4])
qcAdd.barrier(qr)
qcAdd.cx(qr[6], qr[4])
qcAdd.barrier(qr)
qcAdd.p(-np.pi/8, qr[4])
qcAdd.barrier(qr)
qcAdd.cx(qr[6], qr[4])
qcAdd.barrier(qr)
qcAdd.h(qr[4])
qcAdd.barrier(qr)
qcAdd.p(np.pi/4, qr[3])
qcAdd.barrier(qr)
qcAdd.cx(qr[4], qr[3])
qcAdd.barrier(qr)
qcAdd.p(-np.pi/4, qr[3])
qcAdd.barrier(qr)
qcAdd.cx(qr[4], qr[3])
qcAdd.barrier(qr)
qcAdd.p(np.pi/8, qr[3])
qcAdd.barrier(qr)
qcAdd.cx(qr[5], qr[3])
qcAdd.barrier(qr)
qcAdd.p(-np.pi/8, qr[3])
qcAdd.barrier(qr)
qcAdd.cx(qr[5], qr[3])
qcAdd.barrier(qr)
qcAdd.p(0.19634954084936207, qr[3])
qcAdd.barrier(qr)
qcAdd.cx(qr[6], qr[3])
qcAdd.barrier(qr)
qcAdd.p(-0.19634954084936207, qr[3])
qcAdd.barrier(qr)
qcAdd.cx(qr[6], qr[3])
qcAdd.barrier(qr)
qcAdd.h(qr[3])
qcAdd.barrier(qr)

print(qcAdd)