import numpy as np
from qiskit import QuantumCircuit
from qiskit import QuantumRegister
qr = QuantumRegister(5)
qc = QuantumCircuit(qr)

qc.p(np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(-np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(np.pi/2, qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.p(-np.pi/4, qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.p(-np.pi/2, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(np.pi/2, qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.p(-np.pi/2, qr[4])
qc.barrier(qr)
qc.p(-np.pi/8, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(np.pi/8, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(np.pi/2, qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.p(-np.pi/4, qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.p(-np.pi/2, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(np.pi/2, qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.p(-np.pi/2, qr[4])
qc.barrier(qr)
qc.p(-np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.cx(qr[1], qr[4])
qc.barrier(qr)
qc.p(-np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[1], qr[4])
qc.barrier(qr)
qc.p(-np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[1])
qc.barrier(qr)
qc.cx(qr[0], qr[1])
qc.barrier(qr)
qc.p(-np.pi/4, qr[1])
qc.barrier(qr)
qc.p(np.pi/4, qr[0])
qc.barrier(qr)
qc.cx(qr[0], qr[1])
qc.barrier(qr)
qc.p(np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(-np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(np.pi/2, qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.p(-np.pi/4, qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.p(-np.pi/2, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(np.pi/2, qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.p(-np.pi/2, qr[4])
qc.barrier(qr)
qc.p(np.pi/8, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(-np.pi/8, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(np.pi/2, qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.p(-np.pi/4, qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.p(-np.pi/2, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(np.pi/2, qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.p(-np.pi/2, qr[4])
qc.barrier(qr)
qc.p(-np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(np.pi/2, qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.p(-np.pi/4, qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.p(-np.pi/2, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(np.pi/2, qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.p(-np.pi/2, qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.cx(qr[3], qr[4])
qc.barrier(qr)
qc.p(-np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[3], qr[4])
qc.barrier(qr)
qc.p(-np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[3])
qc.barrier(qr)
qc.cx(qr[0], qr[3])
qc.barrier(qr)
qc.p(-np.pi/4, qr[3])
qc.barrier(qr)
qc.p(np.pi/4, qr[0])
qc.barrier(qr)
qc.cx(qr[0], qr[3])
qc.barrier(qr)
qc.p(-np.pi/8, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(np.pi/8, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.cx(qr[1], qr[4])
qc.barrier(qr)
qc.p(-np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[1], qr[4])
qc.barrier(qr)
qc.p(-np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[1])
qc.barrier(qr)
qc.cx(qr[0], qr[1])
qc.barrier(qr)
qc.p(-np.pi/4, qr[1])
qc.barrier(qr)
qc.p(np.pi/4, qr[0])
qc.barrier(qr)
qc.cx(qr[0], qr[1])
qc.barrier(qr)
qc.p(np.pi/8, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(-np.pi/8, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.cx(qr[3], qr[4])
qc.barrier(qr)
qc.p(-np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[3], qr[4])
qc.barrier(qr)
qc.p(-np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[3])
qc.barrier(qr)
qc.cx(qr[0], qr[3])
qc.barrier(qr)
qc.p(-np.pi/4, qr[3])
qc.barrier(qr)
qc.p(np.pi/4, qr[0])
qc.barrier(qr)
qc.cx(qr[0], qr[3])
qc.barrier(qr)
qc.p(-np.pi/8, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(np.pi/8, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.cx(qr[1], qr[4])
qc.barrier(qr)
qc.p(-np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[1], qr[4])
qc.barrier(qr)
qc.p(-np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[1])
qc.barrier(qr)
qc.cx(qr[0], qr[1])
qc.barrier(qr)
qc.p(-np.pi/4, qr[1])
qc.barrier(qr)
qc.p(np.pi/4, qr[0])
qc.barrier(qr)
qc.cx(qr[0], qr[1])
qc.barrier(qr)
qc.p(np.pi/8, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(-np.pi/8, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(np.pi/2, qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.p(-np.pi/4, qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.p(-np.pi/2, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(np.pi/2, qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.p(-np.pi/2, qr[4])
qc.barrier(qr)
qc.p(np.pi/8, qr[3])
qc.barrier(qr)
qc.cx(qr[0], qr[3])
qc.barrier(qr)
qc.p(-np.pi/8, qr[3])
qc.barrier(qr)
qc.cx(qr[0], qr[3])
qc.barrier(qr)
qc.h(qr[3])
qc.barrier(qr)
qc.cx(qr[1], qr[3])
qc.barrier(qr)
qc.p(-np.pi/4, qr[3])
qc.barrier(qr)
qc.cx(qr[0], qr[3])
qc.barrier(qr)
qc.p(np.pi/4, qr[3])
qc.barrier(qr)
qc.cx(qr[1], qr[3])
qc.barrier(qr)
qc.p(-np.pi/4, qr[3])
qc.barrier(qr)
qc.cx(qr[0], qr[3])
qc.barrier(qr)
qc.p(np.pi/4, qr[3])
qc.barrier(qr)
qc.h(qr[3])
qc.barrier(qr)
qc.p(np.pi/4, qr[1])
qc.barrier(qr)
qc.cx(qr[0], qr[1])
qc.barrier(qr)
qc.p(-np.pi/4, qr[1])
qc.barrier(qr)
qc.p(np.pi/4, qr[0])
qc.barrier(qr)
qc.cx(qr[0], qr[1])
qc.barrier(qr)
qc.p(-np.pi/8, qr[3])
qc.barrier(qr)
qc.cx(qr[0], qr[3])
qc.barrier(qr)
qc.p(np.pi/8, qr[3])
qc.barrier(qr)
qc.cx(qr[0], qr[3])
qc.barrier(qr)
qc.p(np.pi/8, qr[1])
qc.barrier(qr)
qc.cx(qr[0], qr[1])
qc.barrier(qr)
qc.p(-np.pi/8, qr[1])
qc.barrier(qr)
qc.cx(qr[0], qr[1])
qc.barrier(qr)
qc.h(qr[3])
qc.barrier(qr)
qc.cx(qr[1], qr[3])
qc.barrier(qr)
qc.p(-np.pi/4, qr[3])
qc.barrier(qr)
qc.cx(qr[0], qr[3])
qc.barrier(qr)
qc.p(np.pi/4, qr[3])
qc.barrier(qr)
qc.cx(qr[1], qr[3])
qc.barrier(qr)
qc.p(-np.pi/4, qr[3])
qc.barrier(qr)
qc.cx(qr[0], qr[3])
qc.barrier(qr)
qc.p(np.pi/4, qr[3])
qc.barrier(qr)
qc.h(qr[3])
qc.barrier(qr)
qc.p(np.pi/4, qr[1])
qc.barrier(qr)
qc.cx(qr[0], qr[1])
qc.barrier(qr)
qc.p(-np.pi/4, qr[1])
qc.barrier(qr)
qc.p(np.pi/4, qr[0])
qc.barrier(qr)
qc.cx(qr[0], qr[1])
qc.barrier(qr)
qc.p(-0.19634954084936207, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(0.19634954084936207, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.cx(qr[1], qr[4])
qc.barrier(qr)
qc.p(-np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[1], qr[4])
qc.barrier(qr)
qc.p(-np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[1])
qc.barrier(qr)
qc.cx(qr[0], qr[1])
qc.barrier(qr)
qc.p(-np.pi/4, qr[1])
qc.barrier(qr)
qc.p(np.pi/4, qr[0])
qc.barrier(qr)
qc.cx(qr[0], qr[1])
qc.barrier(qr)
qc.p(0.19634954084936207, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(-0.19634954084936207, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.cx(qr[1], qr[4])
qc.barrier(qr)
qc.p(-np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[1], qr[4])
qc.barrier(qr)
qc.p(-np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[1])
qc.barrier(qr)
qc.cx(qr[0], qr[1])
qc.barrier(qr)
qc.p(-np.pi/4, qr[1])
qc.barrier(qr)
qc.p(np.pi/4, qr[0])
qc.barrier(qr)
qc.cx(qr[0], qr[1])
qc.barrier(qr)
qc.p(np.pi/2, qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.p(-np.pi/4, qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.p(-np.pi/2, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(np.pi/2, qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.p(-np.pi/2, qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.cx(qr[2], qr[4])
qc.barrier(qr)
qc.p(-np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[2], qr[4])
qc.barrier(qr)
qc.p(-np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[2])
qc.barrier(qr)
qc.cx(qr[0], qr[2])
qc.barrier(qr)
qc.p(-np.pi/4, qr[2])
qc.barrier(qr)
qc.p(np.pi/4, qr[0])
qc.barrier(qr)
qc.cx(qr[0], qr[2])
qc.barrier(qr)
qc.p(-np.pi/8, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(np.pi/8, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.cx(qr[1], qr[4])
qc.barrier(qr)
qc.p(-np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[1], qr[4])
qc.barrier(qr)
qc.p(-np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[1])
qc.barrier(qr)
qc.cx(qr[0], qr[1])
qc.barrier(qr)
qc.p(-np.pi/4, qr[1])
qc.barrier(qr)
qc.p(np.pi/4, qr[0])
qc.barrier(qr)
qc.cx(qr[0], qr[1])
qc.barrier(qr)
qc.p(np.pi/8, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(-np.pi/8, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.cx(qr[2], qr[4])
qc.barrier(qr)
qc.p(-np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[2], qr[4])
qc.barrier(qr)
qc.p(-np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[2])
qc.barrier(qr)
qc.cx(qr[0], qr[2])
qc.barrier(qr)
qc.p(-np.pi/4, qr[2])
qc.barrier(qr)
qc.p(np.pi/4, qr[0])
qc.barrier(qr)
qc.cx(qr[0], qr[2])
qc.barrier(qr)
qc.p(-np.pi/8, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(np.pi/8, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.cx(qr[1], qr[4])
qc.barrier(qr)
qc.p(-np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[1], qr[4])
qc.barrier(qr)
qc.p(-np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[1])
qc.barrier(qr)
qc.cx(qr[0], qr[1])
qc.barrier(qr)
qc.p(-np.pi/4, qr[1])
qc.barrier(qr)
qc.p(np.pi/4, qr[0])
qc.barrier(qr)
qc.cx(qr[0], qr[1])
qc.barrier(qr)
qc.p(np.pi/8, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(-np.pi/8, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(np.pi/2, qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.p(-np.pi/4, qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.p(-np.pi/2, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(np.pi/2, qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.p(-np.pi/2, qr[4])
qc.barrier(qr)
qc.p(np.pi/8, qr[2])
qc.barrier(qr)
qc.cx(qr[0], qr[2])
qc.barrier(qr)
qc.p(-np.pi/8, qr[2])
qc.barrier(qr)
qc.cx(qr[0], qr[2])
qc.barrier(qr)
qc.h(qr[2])
qc.barrier(qr)
qc.cx(qr[1], qr[2])
qc.barrier(qr)
qc.p(-np.pi/4, qr[2])
qc.barrier(qr)
qc.cx(qr[0], qr[2])
qc.barrier(qr)
qc.p(np.pi/4, qr[2])
qc.barrier(qr)
qc.cx(qr[1], qr[2])
qc.barrier(qr)
qc.p(-np.pi/4, qr[2])
qc.barrier(qr)
qc.cx(qr[0], qr[2])
qc.barrier(qr)
qc.p(np.pi/4, qr[2])
qc.barrier(qr)
qc.h(qr[2])
qc.barrier(qr)
qc.p(np.pi/4, qr[1])
qc.barrier(qr)
qc.cx(qr[0], qr[1])
qc.barrier(qr)
qc.p(-np.pi/4, qr[1])
qc.barrier(qr)
qc.p(np.pi/4, qr[0])
qc.barrier(qr)
qc.cx(qr[0], qr[1])
qc.barrier(qr)
qc.p(-np.pi/8, qr[2])
qc.barrier(qr)
qc.cx(qr[0], qr[2])
qc.barrier(qr)
qc.p(np.pi/8, qr[2])
qc.barrier(qr)
qc.cx(qr[0], qr[2])
qc.barrier(qr)
qc.p(np.pi/8, qr[1])
qc.barrier(qr)
qc.cx(qr[0], qr[1])
qc.barrier(qr)
qc.p(-np.pi/8, qr[1])
qc.barrier(qr)
qc.cx(qr[0], qr[1])
qc.barrier(qr)
qc.h(qr[2])
qc.barrier(qr)
qc.cx(qr[1], qr[2])
qc.barrier(qr)
qc.p(-np.pi/4, qr[2])
qc.barrier(qr)
qc.cx(qr[0], qr[2])
qc.barrier(qr)
qc.p(np.pi/4, qr[2])
qc.barrier(qr)
qc.cx(qr[1], qr[2])
qc.barrier(qr)
qc.p(-np.pi/4, qr[2])
qc.barrier(qr)
qc.cx(qr[0], qr[2])
qc.barrier(qr)
qc.p(np.pi/4, qr[2])
qc.barrier(qr)
qc.h(qr[2])
qc.barrier(qr)
qc.p(np.pi/4, qr[1])
qc.barrier(qr)
qc.cx(qr[0], qr[1])
qc.barrier(qr)
qc.p(-np.pi/4, qr[1])
qc.barrier(qr)
qc.p(np.pi/4, qr[0])
qc.barrier(qr)
qc.cx(qr[0], qr[1])
qc.barrier(qr)
qc.p(0.19634954084936207, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(-0.19634954084936207, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.cx(qr[1], qr[4])
qc.barrier(qr)
qc.p(-np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[1], qr[4])
qc.barrier(qr)
qc.p(-np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[1])
qc.barrier(qr)
qc.cx(qr[0], qr[1])
qc.barrier(qr)
qc.p(-np.pi/4, qr[1])
qc.barrier(qr)
qc.p(np.pi/4, qr[0])
qc.barrier(qr)
qc.cx(qr[0], qr[1])
qc.barrier(qr)
qc.p(-0.19634954084936207, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(0.19634954084936207, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.cx(qr[1], qr[4])
qc.barrier(qr)
qc.p(-np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[1], qr[4])
qc.barrier(qr)
qc.p(-np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[1])
qc.barrier(qr)
qc.cx(qr[0], qr[1])
qc.barrier(qr)
qc.p(-np.pi/4, qr[1])
qc.barrier(qr)
qc.p(np.pi/4, qr[0])
qc.barrier(qr)
qc.cx(qr[0], qr[1])
qc.barrier(qr)
qc.p(np.pi/2, qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.p(-np.pi/4, qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.p(-np.pi/2, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(np.pi/2, qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.p(-np.pi/2, qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.cx(qr[3], qr[4])
qc.barrier(qr)
qc.p(-np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[3], qr[4])
qc.barrier(qr)
qc.p(-np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[3])
qc.barrier(qr)
qc.cx(qr[0], qr[3])
qc.barrier(qr)
qc.p(-np.pi/4, qr[3])
qc.barrier(qr)
qc.p(np.pi/4, qr[0])
qc.barrier(qr)
qc.cx(qr[0], qr[3])
qc.barrier(qr)
qc.p(-np.pi/8, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(np.pi/8, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.cx(qr[1], qr[4])
qc.barrier(qr)
qc.p(-np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[1], qr[4])
qc.barrier(qr)
qc.p(-np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[1])
qc.barrier(qr)
qc.cx(qr[0], qr[1])
qc.barrier(qr)
qc.p(-np.pi/4, qr[1])
qc.barrier(qr)
qc.p(np.pi/4, qr[0])
qc.barrier(qr)
qc.cx(qr[0], qr[1])
qc.barrier(qr)
qc.p(np.pi/8, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(-np.pi/8, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.cx(qr[3], qr[4])
qc.barrier(qr)
qc.p(-np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[3], qr[4])
qc.barrier(qr)
qc.p(-np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[3])
qc.barrier(qr)
qc.cx(qr[0], qr[3])
qc.barrier(qr)
qc.p(-np.pi/4, qr[3])
qc.barrier(qr)
qc.p(np.pi/4, qr[0])
qc.barrier(qr)
qc.cx(qr[0], qr[3])
qc.barrier(qr)
qc.p(-np.pi/8, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(np.pi/8, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.cx(qr[1], qr[4])
qc.barrier(qr)
qc.p(-np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[1], qr[4])
qc.barrier(qr)
qc.p(-np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[1])
qc.barrier(qr)
qc.cx(qr[0], qr[1])
qc.barrier(qr)
qc.p(-np.pi/4, qr[1])
qc.barrier(qr)
qc.p(np.pi/4, qr[0])
qc.barrier(qr)
qc.cx(qr[0], qr[1])
qc.barrier(qr)
qc.p(np.pi/8, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(-np.pi/8, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(np.pi/2, qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.p(-np.pi/4, qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.p(-np.pi/2, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(np.pi/2, qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.p(-np.pi/2, qr[4])
qc.barrier(qr)
qc.p(np.pi/8, qr[3])
qc.barrier(qr)
qc.cx(qr[0], qr[3])
qc.barrier(qr)
qc.p(-np.pi/8, qr[3])
qc.barrier(qr)
qc.cx(qr[0], qr[3])
qc.barrier(qr)
qc.h(qr[3])
qc.barrier(qr)
qc.cx(qr[1], qr[3])
qc.barrier(qr)
qc.p(-np.pi/4, qr[3])
qc.barrier(qr)
qc.cx(qr[0], qr[3])
qc.barrier(qr)
qc.p(np.pi/4, qr[3])
qc.barrier(qr)
qc.cx(qr[1], qr[3])
qc.barrier(qr)
qc.p(-np.pi/4, qr[3])
qc.barrier(qr)
qc.cx(qr[0], qr[3])
qc.barrier(qr)
qc.p(np.pi/4, qr[3])
qc.barrier(qr)
qc.h(qr[3])
qc.barrier(qr)
qc.p(np.pi/4, qr[1])
qc.barrier(qr)
qc.cx(qr[0], qr[1])
qc.barrier(qr)
qc.p(-np.pi/4, qr[1])
qc.barrier(qr)
qc.p(np.pi/4, qr[0])
qc.barrier(qr)
qc.cx(qr[0], qr[1])
qc.barrier(qr)
qc.p(-np.pi/8, qr[3])
qc.barrier(qr)
qc.cx(qr[0], qr[3])
qc.barrier(qr)
qc.p(np.pi/8, qr[3])
qc.barrier(qr)
qc.cx(qr[0], qr[3])
qc.barrier(qr)
qc.p(np.pi/8, qr[1])
qc.barrier(qr)
qc.cx(qr[0], qr[1])
qc.barrier(qr)
qc.p(-np.pi/8, qr[1])
qc.barrier(qr)
qc.cx(qr[0], qr[1])
qc.barrier(qr)
qc.h(qr[3])
qc.barrier(qr)
qc.cx(qr[1], qr[3])
qc.barrier(qr)
qc.p(-np.pi/4, qr[3])
qc.barrier(qr)
qc.cx(qr[0], qr[3])
qc.barrier(qr)
qc.p(np.pi/4, qr[3])
qc.barrier(qr)
qc.cx(qr[1], qr[3])
qc.barrier(qr)
qc.p(-np.pi/4, qr[3])
qc.barrier(qr)
qc.cx(qr[0], qr[3])
qc.barrier(qr)
qc.p(np.pi/4, qr[3])
qc.barrier(qr)
qc.h(qr[3])
qc.barrier(qr)
qc.p(np.pi/4, qr[1])
qc.barrier(qr)
qc.cx(qr[0], qr[1])
qc.barrier(qr)
qc.p(-np.pi/4, qr[1])
qc.barrier(qr)
qc.p(np.pi/4, qr[0])
qc.barrier(qr)
qc.cx(qr[0], qr[1])
qc.barrier(qr)
qc.p(-0.19634954084936207, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(0.19634954084936207, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.cx(qr[1], qr[4])
qc.barrier(qr)
qc.p(-np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[1], qr[4])
qc.barrier(qr)
qc.p(-np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[1])
qc.barrier(qr)
qc.cx(qr[0], qr[1])
qc.barrier(qr)
qc.p(-np.pi/4, qr[1])
qc.barrier(qr)
qc.p(np.pi/4, qr[0])
qc.barrier(qr)
qc.cx(qr[0], qr[1])
qc.barrier(qr)
qc.p(0.19634954084936207, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(-0.19634954084936207, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.cx(qr[1], qr[4])
qc.barrier(qr)
qc.p(-np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[1], qr[4])
qc.barrier(qr)
qc.p(-np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[1])
qc.barrier(qr)
qc.cx(qr[0], qr[1])
qc.barrier(qr)
qc.p(-np.pi/4, qr[1])
qc.barrier(qr)
qc.p(np.pi/4, qr[0])
qc.barrier(qr)
qc.cx(qr[0], qr[1])
qc.barrier(qr)
qc.p(np.pi/2, qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.p(-np.pi/4, qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.p(-np.pi/2, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(np.pi/2, qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.p(-np.pi/2, qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.cx(qr[2], qr[4])
qc.barrier(qr)
qc.p(-np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[2], qr[4])
qc.barrier(qr)
qc.p(-np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[2])
qc.barrier(qr)
qc.cx(qr[0], qr[2])
qc.barrier(qr)
qc.p(-np.pi/4, qr[2])
qc.barrier(qr)
qc.p(np.pi/4, qr[0])
qc.barrier(qr)
qc.cx(qr[0], qr[2])
qc.barrier(qr)
qc.p(-np.pi/8, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(np.pi/8, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.cx(qr[1], qr[4])
qc.barrier(qr)
qc.p(-np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[1], qr[4])
qc.barrier(qr)
qc.p(-np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[1])
qc.barrier(qr)
qc.cx(qr[0], qr[1])
qc.barrier(qr)
qc.p(-np.pi/4, qr[1])
qc.barrier(qr)
qc.p(np.pi/4, qr[0])
qc.barrier(qr)
qc.cx(qr[0], qr[1])
qc.barrier(qr)
qc.p(np.pi/8, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(-np.pi/8, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.cx(qr[2], qr[4])
qc.barrier(qr)
qc.p(-np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[2], qr[4])
qc.barrier(qr)
qc.p(-np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[2])
qc.barrier(qr)
qc.cx(qr[0], qr[2])
qc.barrier(qr)
qc.p(-np.pi/4, qr[2])
qc.barrier(qr)
qc.p(np.pi/4, qr[0])
qc.barrier(qr)
qc.cx(qr[0], qr[2])
qc.barrier(qr)
qc.p(-np.pi/8, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(np.pi/8, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.cx(qr[1], qr[4])
qc.barrier(qr)
qc.p(-np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[1], qr[4])
qc.barrier(qr)
qc.p(-np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[1])
qc.barrier(qr)
qc.cx(qr[0], qr[1])
qc.barrier(qr)
qc.p(-np.pi/4, qr[1])
qc.barrier(qr)
qc.p(np.pi/4, qr[0])
qc.barrier(qr)
qc.cx(qr[0], qr[1])
qc.barrier(qr)
qc.p(np.pi/8, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(-np.pi/8, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(np.pi/2, qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.p(-np.pi/4, qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.p(-np.pi/2, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(np.pi/2, qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.p(-np.pi/2, qr[4])
qc.barrier(qr)
qc.p(np.pi/8, qr[2])
qc.barrier(qr)
qc.cx(qr[0], qr[2])
qc.barrier(qr)
qc.p(-np.pi/8, qr[2])
qc.barrier(qr)
qc.cx(qr[0], qr[2])
qc.barrier(qr)
qc.h(qr[2])
qc.barrier(qr)
qc.cx(qr[1], qr[2])
qc.barrier(qr)
qc.p(-np.pi/4, qr[2])
qc.barrier(qr)
qc.cx(qr[0], qr[2])
qc.barrier(qr)
qc.p(np.pi/4, qr[2])
qc.barrier(qr)
qc.cx(qr[1], qr[2])
qc.barrier(qr)
qc.p(-np.pi/4, qr[2])
qc.barrier(qr)
qc.cx(qr[0], qr[2])
qc.barrier(qr)
qc.p(np.pi/4, qr[2])
qc.barrier(qr)
qc.h(qr[2])
qc.barrier(qr)
qc.p(np.pi/4, qr[1])
qc.barrier(qr)
qc.cx(qr[0], qr[1])
qc.barrier(qr)
qc.p(-np.pi/4, qr[1])
qc.barrier(qr)
qc.p(np.pi/4, qr[0])
qc.barrier(qr)
qc.cx(qr[0], qr[1])
qc.barrier(qr)
qc.p(-np.pi/8, qr[2])
qc.barrier(qr)
qc.cx(qr[0], qr[2])
qc.barrier(qr)
qc.p(np.pi/8, qr[2])
qc.barrier(qr)
qc.cx(qr[0], qr[2])
qc.barrier(qr)
qc.p(np.pi/8, qr[1])
qc.barrier(qr)
qc.cx(qr[0], qr[1])
qc.barrier(qr)
qc.p(-np.pi/8, qr[1])
qc.barrier(qr)
qc.cx(qr[0], qr[1])
qc.barrier(qr)
qc.h(qr[2])
qc.barrier(qr)
qc.cx(qr[1], qr[2])
qc.barrier(qr)
qc.p(-np.pi/4, qr[2])
qc.barrier(qr)
qc.cx(qr[0], qr[2])
qc.barrier(qr)
qc.p(np.pi/4, qr[2])
qc.barrier(qr)
qc.cx(qr[1], qr[2])
qc.barrier(qr)
qc.p(-np.pi/4, qr[2])
qc.barrier(qr)
qc.cx(qr[0], qr[2])
qc.barrier(qr)
qc.p(np.pi/4, qr[2])
qc.barrier(qr)
qc.h(qr[2])
qc.barrier(qr)
qc.p(np.pi/4, qr[1])
qc.barrier(qr)
qc.cx(qr[0], qr[1])
qc.barrier(qr)
qc.p(-np.pi/4, qr[1])
qc.barrier(qr)
qc.p(np.pi/4, qr[0])
qc.barrier(qr)
qc.cx(qr[0], qr[1])
qc.barrier(qr)
qc.p(0.19634954084936207, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(-0.19634954084936207, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.cx(qr[1], qr[4])
qc.barrier(qr)
qc.p(-np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[1], qr[4])
qc.barrier(qr)
qc.p(-np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[1])
qc.barrier(qr)
qc.cx(qr[0], qr[1])
qc.barrier(qr)
qc.p(-np.pi/4, qr[1])
qc.barrier(qr)
qc.p(np.pi/4, qr[0])
qc.barrier(qr)
qc.cx(qr[0], qr[1])
qc.barrier(qr)
qc.p(-0.19634954084936207, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(0.19634954084936207, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.cx(qr[1], qr[4])
qc.barrier(qr)
qc.p(-np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[1], qr[4])
qc.barrier(qr)
qc.p(-np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[1])
qc.barrier(qr)
qc.cx(qr[0], qr[1])
qc.barrier(qr)
qc.p(-np.pi/4, qr[1])
qc.barrier(qr)
qc.p(np.pi/4, qr[0])
qc.barrier(qr)
qc.cx(qr[0], qr[1])
qc.barrier(qr)
qc.p(np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(-np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(np.pi/2, qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.p(-np.pi/4, qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.p(-np.pi/2, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(np.pi/2, qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.p(-np.pi/2, qr[4])
qc.barrier(qr)
qc.p(-np.pi/8, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(np.pi/8, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(np.pi/2, qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.p(-np.pi/4, qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.p(-np.pi/2, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(np.pi/2, qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.p(-np.pi/2, qr[4])
qc.barrier(qr)
qc.p(-np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.cx(qr[1], qr[4])
qc.barrier(qr)
qc.p(-np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[1], qr[4])
qc.barrier(qr)
qc.p(-np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[1])
qc.barrier(qr)
qc.cx(qr[0], qr[1])
qc.barrier(qr)
qc.p(-np.pi/4, qr[1])
qc.barrier(qr)
qc.p(np.pi/4, qr[0])
qc.barrier(qr)
qc.cx(qr[0], qr[1])
qc.barrier(qr)
qc.p(np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(-np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(np.pi/2, qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.p(-np.pi/4, qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.p(-np.pi/2, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(np.pi/2, qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.p(-np.pi/2, qr[4])
qc.barrier(qr)
qc.p(np.pi/8, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(-np.pi/8, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(np.pi/2, qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.p(-np.pi/4, qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.p(-np.pi/2, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(np.pi/2, qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.p(-np.pi/2, qr[4])
qc.barrier(qr)
qc.p(-np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[0], qr[4])
qc.barrier(qr)
qc.p(0.19634954084936207, qr[3])
qc.barrier(qr)
qc.cx(qr[0], qr[3])
qc.barrier(qr)
qc.p(-0.19634954084936207, qr[3])
qc.barrier(qr)
qc.cx(qr[0], qr[3])
qc.barrier(qr)
qc.h(qr[3])
qc.barrier(qr)
qc.cx(qr[1], qr[3])
qc.barrier(qr)
qc.p(-np.pi/4, qr[3])
qc.barrier(qr)
qc.cx(qr[0], qr[3])
qc.barrier(qr)
qc.p(np.pi/4, qr[3])
qc.barrier(qr)
qc.cx(qr[1], qr[3])
qc.barrier(qr)
qc.p(-np.pi/4, qr[3])
qc.barrier(qr)
qc.cx(qr[0], qr[3])
qc.barrier(qr)
qc.p(np.pi/4, qr[3])
qc.barrier(qr)
qc.h(qr[3])
qc.barrier(qr)
qc.p(np.pi/4, qr[1])
qc.barrier(qr)
qc.cx(qr[0], qr[1])
qc.barrier(qr)
qc.p(-np.pi/4, qr[1])
qc.barrier(qr)
qc.p(np.pi/4, qr[0])
qc.barrier(qr)
qc.cx(qr[0], qr[1])
qc.barrier(qr)
qc.p(-0.19634954084936207, qr[3])
qc.barrier(qr)
qc.cx(qr[0], qr[3])
qc.barrier(qr)
qc.p(0.19634954084936207, qr[3])
qc.barrier(qr)
qc.cx(qr[0], qr[3])
qc.barrier(qr)
qc.h(qr[3])
qc.barrier(qr)
qc.cx(qr[1], qr[3])
qc.barrier(qr)
qc.p(-np.pi/4, qr[3])
qc.barrier(qr)
qc.cx(qr[0], qr[3])
qc.barrier(qr)
qc.p(np.pi/4, qr[3])
qc.barrier(qr)
qc.cx(qr[1], qr[3])
qc.barrier(qr)
qc.p(-np.pi/4, qr[3])
qc.barrier(qr)
qc.cx(qr[0], qr[3])
qc.barrier(qr)
qc.p(np.pi/4, qr[3])
qc.barrier(qr)
qc.h(qr[3])
qc.barrier(qr)
qc.p(np.pi/4, qr[1])
qc.barrier(qr)
qc.cx(qr[0], qr[1])
qc.barrier(qr)
qc.p(-np.pi/4, qr[1])
qc.barrier(qr)
qc.p(np.pi/4, qr[0])
qc.barrier(qr)
qc.cx(qr[0], qr[1])
qc.barrier(qr)
qc.p(np.pi/2, qr[3])
qc.barrier(qr)
qc.h(qr[3])
qc.barrier(qr)
qc.p(-np.pi/4, qr[3])
qc.barrier(qr)
qc.h(qr[3])
qc.barrier(qr)
qc.p(-np.pi/2, qr[3])
qc.barrier(qr)
qc.cx(qr[0], qr[3])
qc.barrier(qr)
qc.p(np.pi/2, qr[3])
qc.barrier(qr)
qc.h(qr[3])
qc.barrier(qr)
qc.p(np.pi/4, qr[3])
qc.barrier(qr)
qc.h(qr[3])
qc.barrier(qr)
qc.p(-np.pi/2, qr[3])
qc.barrier(qr)
qc.h(qr[3])
qc.barrier(qr)
qc.cx(qr[2], qr[3])
qc.barrier(qr)
qc.p(-np.pi/4, qr[3])
qc.barrier(qr)
qc.cx(qr[0], qr[3])
qc.barrier(qr)
qc.p(np.pi/4, qr[3])
qc.barrier(qr)
qc.cx(qr[2], qr[3])
qc.barrier(qr)
qc.p(-np.pi/4, qr[3])
qc.barrier(qr)
qc.cx(qr[0], qr[3])
qc.barrier(qr)
qc.p(np.pi/4, qr[3])
qc.barrier(qr)
qc.h(qr[3])
qc.barrier(qr)
qc.p(np.pi/4, qr[2])
qc.barrier(qr)
qc.cx(qr[0], qr[2])
qc.barrier(qr)
qc.p(-np.pi/4, qr[2])
qc.barrier(qr)
qc.p(np.pi/4, qr[0])
qc.barrier(qr)
qc.cx(qr[0], qr[2])
qc.barrier(qr)
qc.p(-np.pi/8, qr[3])
qc.barrier(qr)
qc.cx(qr[0], qr[3])
qc.barrier(qr)
qc.p(np.pi/8, qr[3])
qc.barrier(qr)
qc.cx(qr[0], qr[3])
qc.barrier(qr)
qc.h(qr[3])
qc.barrier(qr)
qc.cx(qr[1], qr[3])
qc.barrier(qr)
qc.p(-np.pi/4, qr[3])
qc.barrier(qr)
qc.cx(qr[0], qr[3])
qc.barrier(qr)
qc.p(np.pi/4, qr[3])
qc.barrier(qr)
qc.cx(qr[1], qr[3])
qc.barrier(qr)
qc.p(-np.pi/4, qr[3])
qc.barrier(qr)
qc.cx(qr[0], qr[3])
qc.barrier(qr)
qc.p(np.pi/4, qr[3])
qc.barrier(qr)
qc.h(qr[3])
qc.barrier(qr)
qc.p(np.pi/4, qr[1])
qc.barrier(qr)
qc.cx(qr[0], qr[1])
qc.barrier(qr)
qc.p(-np.pi/4, qr[1])
qc.barrier(qr)
qc.p(np.pi/4, qr[0])
qc.barrier(qr)
qc.cx(qr[0], qr[1])
qc.barrier(qr)
qc.p(np.pi/8, qr[3])
qc.barrier(qr)
qc.cx(qr[0], qr[3])
qc.barrier(qr)
qc.p(-np.pi/8, qr[3])
qc.barrier(qr)
qc.cx(qr[0], qr[3])
qc.barrier(qr)
qc.h(qr[3])
qc.barrier(qr)
qc.cx(qr[2], qr[3])
qc.barrier(qr)
qc.p(-np.pi/4, qr[3])
qc.barrier(qr)
qc.cx(qr[0], qr[3])
qc.barrier(qr)
qc.p(np.pi/4, qr[3])
qc.barrier(qr)
qc.cx(qr[2], qr[3])
qc.barrier(qr)
qc.p(-np.pi/4, qr[3])
qc.barrier(qr)
qc.cx(qr[0], qr[3])
qc.barrier(qr)
qc.p(np.pi/4, qr[3])
qc.barrier(qr)
qc.h(qr[3])
qc.barrier(qr)
qc.p(np.pi/4, qr[2])
qc.barrier(qr)
qc.cx(qr[0], qr[2])
qc.barrier(qr)
qc.p(-np.pi/4, qr[2])
qc.barrier(qr)
qc.p(np.pi/4, qr[0])
qc.barrier(qr)
qc.cx(qr[0], qr[2])
qc.barrier(qr)
qc.p(-np.pi/8, qr[3])
qc.barrier(qr)
qc.cx(qr[0], qr[3])
qc.barrier(qr)
qc.p(np.pi/8, qr[3])
qc.barrier(qr)
qc.cx(qr[0], qr[3])
qc.barrier(qr)
qc.h(qr[3])
qc.barrier(qr)
qc.cx(qr[1], qr[3])
qc.barrier(qr)
qc.p(-np.pi/4, qr[3])
qc.barrier(qr)
qc.cx(qr[0], qr[3])
qc.barrier(qr)
qc.p(np.pi/4, qr[3])
qc.barrier(qr)
qc.cx(qr[1], qr[3])
qc.barrier(qr)
qc.p(-np.pi/4, qr[3])
qc.barrier(qr)
qc.cx(qr[0], qr[3])
qc.barrier(qr)
qc.p(np.pi/4, qr[3])
qc.barrier(qr)
qc.h(qr[3])
qc.barrier(qr)
qc.p(np.pi/4, qr[1])
qc.barrier(qr)
qc.cx(qr[0], qr[1])
qc.barrier(qr)
qc.p(-np.pi/4, qr[1])
qc.barrier(qr)
qc.p(np.pi/4, qr[0])
qc.barrier(qr)
qc.cx(qr[0], qr[1])
qc.barrier(qr)
qc.p(np.pi/8, qr[3])
qc.barrier(qr)
qc.cx(qr[0], qr[3])
qc.barrier(qr)
qc.p(-np.pi/8, qr[3])
qc.barrier(qr)
qc.cx(qr[0], qr[3])
qc.barrier(qr)
qc.p(np.pi/2, qr[3])
qc.barrier(qr)
qc.h(qr[3])
qc.barrier(qr)
qc.p(-np.pi/4, qr[3])
qc.barrier(qr)
qc.h(qr[3])
qc.barrier(qr)
qc.p(-np.pi/2, qr[3])
qc.barrier(qr)
qc.cx(qr[0], qr[3])
qc.barrier(qr)
qc.p(np.pi/2, qr[3])
qc.barrier(qr)
qc.h(qr[3])
qc.barrier(qr)
qc.p(np.pi/4, qr[3])
qc.barrier(qr)
qc.h(qr[3])
qc.barrier(qr)
qc.p(-np.pi/2, qr[3])
qc.barrier(qr)
qc.p(np.pi/8, qr[2])
qc.barrier(qr)
qc.cx(qr[0], qr[2])
qc.barrier(qr)
qc.p(-np.pi/8, qr[2])
qc.barrier(qr)
qc.cx(qr[0], qr[2])
qc.barrier(qr)
qc.h(qr[2])
qc.barrier(qr)
qc.cx(qr[1], qr[2])
qc.barrier(qr)
qc.p(-np.pi/4, qr[2])
qc.barrier(qr)
qc.cx(qr[0], qr[2])
qc.barrier(qr)
qc.p(np.pi/4, qr[2])
qc.barrier(qr)
qc.cx(qr[1], qr[2])
qc.barrier(qr)
qc.p(-np.pi/4, qr[2])
qc.barrier(qr)
qc.cx(qr[0], qr[2])
qc.barrier(qr)
qc.p(np.pi/4, qr[2])
qc.barrier(qr)
qc.h(qr[2])
qc.barrier(qr)
qc.p(np.pi/4, qr[1])
qc.barrier(qr)
qc.cx(qr[0], qr[1])
qc.barrier(qr)
qc.p(-np.pi/4, qr[1])
qc.barrier(qr)
qc.p(np.pi/4, qr[0])
qc.barrier(qr)
qc.cx(qr[0], qr[1])
qc.barrier(qr)
qc.p(-np.pi/8, qr[2])
qc.barrier(qr)
qc.cx(qr[0], qr[2])
qc.barrier(qr)
qc.p(np.pi/8, qr[2])
qc.barrier(qr)
qc.cx(qr[0], qr[2])
qc.barrier(qr)
qc.p(np.pi/8, qr[1])
qc.barrier(qr)
qc.cx(qr[0], qr[1])
qc.barrier(qr)
qc.p(-np.pi/8, qr[1])
qc.barrier(qr)
qc.cx(qr[0], qr[1])
qc.barrier(qr)
qc.h(qr[2])
qc.barrier(qr)
qc.cx(qr[1], qr[2])
qc.barrier(qr)
qc.p(-np.pi/4, qr[2])
qc.barrier(qr)
qc.cx(qr[0], qr[2])
qc.barrier(qr)
qc.p(np.pi/4, qr[2])
qc.barrier(qr)
qc.cx(qr[1], qr[2])
qc.barrier(qr)
qc.p(-np.pi/4, qr[2])
qc.barrier(qr)
qc.cx(qr[0], qr[2])
qc.barrier(qr)
qc.p(np.pi/4, qr[2])
qc.barrier(qr)
qc.h(qr[2])
qc.barrier(qr)
qc.p(np.pi/4, qr[1])
qc.barrier(qr)
qc.cx(qr[0], qr[1])
qc.barrier(qr)
qc.p(-np.pi/4, qr[1])
qc.barrier(qr)
qc.p(np.pi/4, qr[0])
qc.barrier(qr)
qc.cx(qr[0], qr[1])
qc.barrier(qr)
qc.p(-0.19634954084936207, qr[3])
qc.barrier(qr)
qc.cx(qr[0], qr[3])
qc.barrier(qr)
qc.p(0.19634954084936207, qr[3])
qc.barrier(qr)
qc.cx(qr[0], qr[3])
qc.barrier(qr)
qc.h(qr[3])
qc.barrier(qr)
qc.cx(qr[1], qr[3])
qc.barrier(qr)
qc.p(-np.pi/4, qr[3])
qc.barrier(qr)
qc.cx(qr[0], qr[3])
qc.barrier(qr)
qc.p(np.pi/4, qr[3])
qc.barrier(qr)
qc.cx(qr[1], qr[3])
qc.barrier(qr)
qc.p(-np.pi/4, qr[3])
qc.barrier(qr)
qc.cx(qr[0], qr[3])
qc.barrier(qr)
qc.p(np.pi/4, qr[3])
qc.barrier(qr)
qc.h(qr[3])
qc.barrier(qr)
qc.p(np.pi/4, qr[1])
qc.barrier(qr)
qc.cx(qr[0], qr[1])
qc.barrier(qr)
qc.p(-np.pi/4, qr[1])
qc.barrier(qr)
qc.p(np.pi/4, qr[0])
qc.barrier(qr)
qc.cx(qr[0], qr[1])
qc.barrier(qr)
qc.p(0.19634954084936207, qr[3])
qc.barrier(qr)
qc.cx(qr[0], qr[3])
qc.barrier(qr)
qc.p(-0.19634954084936207, qr[3])
qc.barrier(qr)
qc.cx(qr[0], qr[3])
qc.barrier(qr)
qc.h(qr[3])
qc.barrier(qr)
qc.cx(qr[1], qr[3])
qc.barrier(qr)
qc.p(-np.pi/4, qr[3])
qc.barrier(qr)
qc.cx(qr[0], qr[3])
qc.barrier(qr)
qc.p(np.pi/4, qr[3])
qc.barrier(qr)
qc.cx(qr[1], qr[3])
qc.barrier(qr)
qc.p(-np.pi/4, qr[3])
qc.barrier(qr)
qc.cx(qr[0], qr[3])
qc.barrier(qr)
qc.p(np.pi/4, qr[3])
qc.barrier(qr)
qc.h(qr[3])
qc.barrier(qr)
qc.p(np.pi/4, qr[1])
qc.barrier(qr)
qc.cx(qr[0], qr[1])
qc.barrier(qr)
qc.p(-np.pi/4, qr[1])
qc.barrier(qr)
qc.p(np.pi/4, qr[0])
qc.barrier(qr)
qc.cx(qr[0], qr[1])
qc.barrier(qr)
qc.p(0.19634954084936207, qr[2])
qc.barrier(qr)
qc.cx(qr[0], qr[2])
qc.barrier(qr)
qc.p(-0.19634954084936207, qr[2])
qc.barrier(qr)
qc.cx(qr[0], qr[2])
qc.barrier(qr)
qc.h(qr[2])
qc.barrier(qr)
qc.cx(qr[1], qr[2])
qc.barrier(qr)
qc.p(-np.pi/4, qr[2])
qc.barrier(qr)
qc.cx(qr[0], qr[2])
qc.barrier(qr)
qc.p(np.pi/4, qr[2])
qc.barrier(qr)
qc.cx(qr[1], qr[2])
qc.barrier(qr)
qc.p(-np.pi/4, qr[2])
qc.barrier(qr)
qc.cx(qr[0], qr[2])
qc.barrier(qr)
qc.p(np.pi/4, qr[2])
qc.barrier(qr)
qc.h(qr[2])
qc.barrier(qr)
qc.p(np.pi/4, qr[1])
qc.barrier(qr)
qc.cx(qr[0], qr[1])
qc.barrier(qr)
qc.p(-np.pi/4, qr[1])
qc.barrier(qr)
qc.p(np.pi/4, qr[0])
qc.barrier(qr)
qc.cx(qr[0], qr[1])
qc.barrier(qr)
qc.p(-0.19634954084936207, qr[2])
qc.barrier(qr)
qc.cx(qr[0], qr[2])
qc.barrier(qr)
qc.p(0.19634954084936207, qr[2])
qc.barrier(qr)
qc.cx(qr[0], qr[2])
qc.barrier(qr)
qc.h(qr[2])
qc.barrier(qr)
qc.cx(qr[1], qr[2])
qc.barrier(qr)
qc.p(-np.pi/4, qr[2])
qc.barrier(qr)
qc.cx(qr[0], qr[2])
qc.barrier(qr)
qc.p(np.pi/4, qr[2])
qc.barrier(qr)
qc.cx(qr[1], qr[2])
qc.barrier(qr)
qc.p(-np.pi/4, qr[2])
qc.barrier(qr)
qc.cx(qr[0], qr[2])
qc.barrier(qr)
qc.p(np.pi/4, qr[2])
qc.barrier(qr)
qc.h(qr[2])
qc.barrier(qr)
qc.p(np.pi/4, qr[1])
qc.barrier(qr)
qc.cx(qr[0], qr[1])
qc.barrier(qr)
qc.p(-np.pi/4, qr[1])
qc.barrier(qr)
qc.p(np.pi/4, qr[0])
qc.barrier(qr)
qc.cx(qr[0], qr[1])
qc.barrier(qr)
qc.p(np.pi/2, qr[3])
qc.barrier(qr)
qc.h(qr[3])
qc.barrier(qr)
qc.p(-np.pi/4, qr[3])
qc.barrier(qr)
qc.h(qr[3])
qc.barrier(qr)
qc.p(-np.pi/2, qr[3])
qc.barrier(qr)
qc.cx(qr[0], qr[3])
qc.barrier(qr)
qc.p(np.pi/2, qr[3])
qc.barrier(qr)
qc.h(qr[3])
qc.barrier(qr)
qc.p(np.pi/4, qr[3])
qc.barrier(qr)
qc.h(qr[3])
qc.barrier(qr)
qc.p(-np.pi/2, qr[3])
qc.barrier(qr)
qc.h(qr[3])
qc.barrier(qr)
qc.cx(qr[2], qr[3])
qc.barrier(qr)
qc.p(-np.pi/4, qr[3])
qc.barrier(qr)
qc.cx(qr[0], qr[3])
qc.barrier(qr)
qc.p(np.pi/4, qr[3])
qc.barrier(qr)
qc.cx(qr[2], qr[3])
qc.barrier(qr)
qc.p(-np.pi/4, qr[3])
qc.barrier(qr)
qc.cx(qr[0], qr[3])
qc.barrier(qr)
qc.p(np.pi/4, qr[3])
qc.barrier(qr)
qc.h(qr[3])
qc.barrier(qr)
qc.p(np.pi/4, qr[2])
qc.barrier(qr)
qc.cx(qr[0], qr[2])
qc.barrier(qr)
qc.p(-np.pi/4, qr[2])
qc.barrier(qr)
qc.p(np.pi/4, qr[0])
qc.barrier(qr)
qc.cx(qr[0], qr[2])
qc.barrier(qr)
qc.p(-np.pi/8, qr[3])
qc.barrier(qr)
qc.cx(qr[0], qr[3])
qc.barrier(qr)
qc.p(np.pi/8, qr[3])
qc.barrier(qr)
qc.cx(qr[0], qr[3])
qc.barrier(qr)
qc.h(qr[3])
qc.barrier(qr)
qc.cx(qr[1], qr[3])
qc.barrier(qr)
qc.p(-np.pi/4, qr[3])
qc.barrier(qr)
qc.cx(qr[0], qr[3])
qc.barrier(qr)
qc.p(np.pi/4, qr[3])
qc.barrier(qr)
qc.cx(qr[1], qr[3])
qc.barrier(qr)
qc.p(-np.pi/4, qr[3])
qc.barrier(qr)
qc.cx(qr[0], qr[3])
qc.barrier(qr)
qc.p(np.pi/4, qr[3])
qc.barrier(qr)
qc.h(qr[3])
qc.barrier(qr)
qc.p(np.pi/4, qr[1])
qc.barrier(qr)
qc.cx(qr[0], qr[1])
qc.barrier(qr)
qc.p(-np.pi/4, qr[1])
qc.barrier(qr)
qc.p(np.pi/4, qr[0])
qc.barrier(qr)
qc.cx(qr[0], qr[1])
qc.barrier(qr)
qc.p(np.pi/8, qr[3])
qc.barrier(qr)
qc.cx(qr[0], qr[3])
qc.barrier(qr)
qc.p(-np.pi/8, qr[3])
qc.barrier(qr)
qc.cx(qr[0], qr[3])
qc.barrier(qr)
qc.h(qr[3])
qc.barrier(qr)
qc.cx(qr[2], qr[3])
qc.barrier(qr)
qc.p(-np.pi/4, qr[3])
qc.barrier(qr)
qc.cx(qr[0], qr[3])
qc.barrier(qr)
qc.p(np.pi/4, qr[3])
qc.barrier(qr)
qc.cx(qr[2], qr[3])
qc.barrier(qr)
qc.p(-np.pi/4, qr[3])
qc.barrier(qr)
qc.cx(qr[0], qr[3])
qc.barrier(qr)
qc.p(np.pi/4, qr[3])
qc.barrier(qr)
qc.h(qr[3])
qc.barrier(qr)
qc.p(np.pi/4, qr[2])
qc.barrier(qr)
qc.cx(qr[0], qr[2])
qc.barrier(qr)
qc.p(-np.pi/4, qr[2])
qc.barrier(qr)
qc.p(np.pi/4, qr[0])
qc.barrier(qr)
qc.cx(qr[0], qr[2])
qc.barrier(qr)
qc.p(-np.pi/8, qr[3])
qc.barrier(qr)
qc.cx(qr[0], qr[3])
qc.barrier(qr)
qc.p(np.pi/8, qr[3])
qc.barrier(qr)
qc.cx(qr[0], qr[3])
qc.barrier(qr)
qc.h(qr[3])
qc.barrier(qr)
qc.cx(qr[1], qr[3])
qc.barrier(qr)
qc.p(-np.pi/4, qr[3])
qc.barrier(qr)
qc.cx(qr[0], qr[3])
qc.barrier(qr)
qc.p(np.pi/4, qr[3])
qc.barrier(qr)
qc.cx(qr[1], qr[3])
qc.barrier(qr)
qc.p(-np.pi/4, qr[3])
qc.barrier(qr)
qc.cx(qr[0], qr[3])
qc.barrier(qr)
qc.p(np.pi/4, qr[3])
qc.barrier(qr)
qc.h(qr[3])
qc.barrier(qr)
qc.p(np.pi/4, qr[1])
qc.barrier(qr)
qc.cx(qr[0], qr[1])
qc.barrier(qr)
qc.p(-np.pi/4, qr[1])
qc.barrier(qr)
qc.p(np.pi/4, qr[0])
qc.barrier(qr)
qc.cx(qr[0], qr[1])
qc.barrier(qr)
qc.p(np.pi/8, qr[3])
qc.barrier(qr)
qc.cx(qr[0], qr[3])
qc.barrier(qr)
qc.p(-np.pi/8, qr[3])
qc.barrier(qr)
qc.cx(qr[0], qr[3])
qc.barrier(qr)
qc.p(np.pi/2, qr[3])
qc.barrier(qr)
qc.h(qr[3])
qc.barrier(qr)
qc.p(-np.pi/4, qr[3])
qc.barrier(qr)
qc.h(qr[3])
qc.barrier(qr)
qc.p(-np.pi/2, qr[3])
qc.barrier(qr)
qc.cx(qr[0], qr[3])
qc.barrier(qr)
qc.p(np.pi/2, qr[3])
qc.barrier(qr)
qc.h(qr[3])
qc.barrier(qr)
qc.p(np.pi/4, qr[3])
qc.barrier(qr)
qc.h(qr[3])
qc.barrier(qr)
qc.p(-np.pi/2, qr[3])
qc.barrier(qr)
qc.p(np.pi/8, qr[2])
qc.barrier(qr)
qc.cx(qr[0], qr[2])
qc.barrier(qr)
qc.p(-np.pi/8, qr[2])
qc.barrier(qr)
qc.cx(qr[0], qr[2])
qc.barrier(qr)
qc.h(qr[2])
qc.barrier(qr)
qc.cx(qr[1], qr[2])
qc.barrier(qr)
qc.p(-np.pi/4, qr[2])
qc.barrier(qr)
qc.cx(qr[0], qr[2])
qc.barrier(qr)
qc.p(np.pi/4, qr[2])
qc.barrier(qr)
qc.cx(qr[1], qr[2])
qc.barrier(qr)
qc.p(-np.pi/4, qr[2])
qc.barrier(qr)
qc.cx(qr[0], qr[2])
qc.barrier(qr)
qc.p(np.pi/4, qr[2])
qc.barrier(qr)
qc.h(qr[2])
qc.barrier(qr)
qc.p(np.pi/4, qr[1])
qc.barrier(qr)
qc.cx(qr[0], qr[1])
qc.barrier(qr)
qc.p(-np.pi/4, qr[1])
qc.barrier(qr)
qc.p(np.pi/4, qr[0])
qc.barrier(qr)
qc.cx(qr[0], qr[1])
qc.barrier(qr)
qc.p(-np.pi/8, qr[2])
qc.barrier(qr)
qc.cx(qr[0], qr[2])
qc.barrier(qr)
qc.p(np.pi/8, qr[2])
qc.barrier(qr)
qc.cx(qr[0], qr[2])
qc.barrier(qr)
qc.p(np.pi/8, qr[1])
qc.barrier(qr)
qc.cx(qr[0], qr[1])
qc.barrier(qr)
qc.p(-np.pi/8, qr[1])
qc.barrier(qr)
qc.cx(qr[0], qr[1])
qc.barrier(qr)
qc.h(qr[2])
qc.barrier(qr)
qc.cx(qr[1], qr[2])
qc.barrier(qr)
qc.p(-np.pi/4, qr[2])
qc.barrier(qr)
qc.cx(qr[0], qr[2])
qc.barrier(qr)
qc.p(np.pi/4, qr[2])
qc.barrier(qr)
qc.cx(qr[1], qr[2])
qc.barrier(qr)
qc.p(-np.pi/4, qr[2])
qc.barrier(qr)
qc.cx(qr[0], qr[2])
qc.barrier(qr)
qc.p(np.pi/4, qr[2])
qc.barrier(qr)
qc.h(qr[2])
qc.barrier(qr)
qc.p(np.pi/4, qr[1])
qc.barrier(qr)
qc.cx(qr[0], qr[1])
qc.barrier(qr)
qc.p(-np.pi/4, qr[1])
qc.barrier(qr)
qc.p(np.pi/4, qr[0])
qc.barrier(qr)
qc.cx(qr[0], qr[1])
qc.barrier(qr)

print(qc)

qc.draw(output="mpl", plot_barriers=False, filename="TripleCAbs.png")