import numpy as np
from qiskit import QuantumCircuit
from qiskit import QuantumRegister
qr = QuantumRegister(7)
qc = QuantumCircuit(qr)

qc.h(qr[3])
qc.barrier(qr)
qc.p(np.pi/4, qr[3])
qc.barrier(qr)
qc.cx(qr[4], qr[3])
qc.barrier(qr)
qc.p(-np.pi/4, qr[3])
qc.barrier(qr)
qc.cx(qr[4], qr[3])
qc.barrier(qr)
qc.p(np.pi/8, qr[3])
qc.barrier(qr)
qc.cx(qr[5], qr[3])
qc.barrier(qr)
qc.p(-np.pi/8, qr[3])
qc.barrier(qr)
qc.cx(qr[5], qr[3])
qc.barrier(qr)
qc.p(0.19634954084936207, qr[3])
qc.barrier(qr)
qc.cx(qr[6], qr[3])
qc.barrier(qr)
qc.p(-0.19634954084936207, qr[3])
qc.barrier(qr)
qc.cx(qr[6], qr[3])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[5], qr[4])
qc.barrier(qr)
qc.p(-np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[5], qr[4])
qc.barrier(qr)
qc.p(np.pi/8, qr[4])
qc.barrier(qr)
qc.cx(qr[6], qr[4])
qc.barrier(qr)
qc.p(-np.pi/8, qr[4])
qc.barrier(qr)
qc.cx(qr[6], qr[4])
qc.barrier(qr)
qc.h(qr[5])
qc.barrier(qr)
qc.p(np.pi/4, qr[5])
qc.barrier(qr)
qc.cx(qr[6], qr[5])
qc.barrier(qr)
qc.p(-np.pi/4, qr[5])
qc.barrier(qr)
qc.cx(qr[6], qr[5])
qc.barrier(qr)
qc.h(qr[6])
qc.barrier(qr)
qc.p(np.pi/2, qr[3])
qc.barrier(qr)
qc.cx(qr[0], qr[3])
qc.barrier(qr)
qc.p(-np.pi/2, qr[3])
qc.barrier(qr)
qc.cx(qr[0], qr[3])
qc.barrier(qr)
qc.p(np.pi/4, qr[3])
qc.barrier(qr)
qc.cx(qr[1], qr[3])
qc.barrier(qr)
qc.p(-np.pi/4, qr[3])
qc.barrier(qr)
qc.cx(qr[1], qr[3])
qc.barrier(qr)
qc.p(np.pi/8, qr[3])
qc.barrier(qr)
qc.cx(qr[2], qr[3])
qc.barrier(qr)
qc.p(-np.pi/8, qr[3])
qc.barrier(qr)
qc.cx(qr[2], qr[3])
qc.barrier(qr)
qc.p(np.pi/2, qr[4])
qc.barrier(qr)
qc.cx(qr[1], qr[4])
qc.barrier(qr)
qc.p(-np.pi/2, qr[4])
qc.barrier(qr)
qc.cx(qr[1], qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[2], qr[4])
qc.barrier(qr)
qc.p(-np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[2], qr[4])
qc.barrier(qr)
qc.p(np.pi/2, qr[5])
qc.barrier(qr)
qc.cx(qr[2], qr[5])
qc.barrier(qr)
qc.p(-np.pi/2, qr[5])
qc.barrier(qr)
qc.cx(qr[2], qr[5])
qc.barrier(qr)
qc.h(qr[6])
qc.barrier(qr)
qc.cx(qr[6], qr[5])
qc.barrier(qr)
qc.p(np.pi/4, qr[5])
qc.barrier(qr)
qc.cx(qr[6], qr[5])
qc.barrier(qr)
qc.p(-np.pi/4, qr[5])
qc.barrier(qr)
qc.h(qr[5])
qc.barrier(qr)
qc.cx(qr[6], qr[4])
qc.barrier(qr)
qc.p(np.pi/8, qr[4])
qc.barrier(qr)
qc.cx(qr[6], qr[4])
qc.barrier(qr)
qc.p(-np.pi/8, qr[4])
qc.barrier(qr)
qc.cx(qr[5], qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[5], qr[4])
qc.barrier(qr)
qc.p(-np.pi/4, qr[4])
qc.barrier(qr)
qc.h(qr[4])
qc.barrier(qr)
qc.cx(qr[6], qr[3])
qc.barrier(qr)
qc.p(0.19634954084936207, qr[3])
qc.barrier(qr)
qc.cx(qr[6], qr[3])
qc.barrier(qr)
qc.p(-0.19634954084936207, qr[3])
qc.barrier(qr)
qc.cx(qr[5], qr[3])
qc.barrier(qr)
qc.p(np.pi/8, qr[3])
qc.barrier(qr)
qc.cx(qr[5], qr[3])
qc.barrier(qr)
qc.p(-np.pi/8, qr[3])
qc.barrier(qr)
qc.cx(qr[4], qr[3])
qc.barrier(qr)
qc.p(np.pi/4, qr[3])
qc.barrier(qr)
qc.cx(qr[4], qr[3])
qc.barrier(qr)
qc.p(-np.pi/4, qr[3])
qc.barrier(qr)
qc.h(qr[3])
qc.barrier(qr)

print(qc)