import numpy as np
from qiskit import QuantumCircuit
from qiskit import QuantumRegister
qr = QuantumRegister(4)
qcQFT = QuantumCircuit(qr)

qcQFT.h(qr[0])
qcQFT.barrier(qr)
qcQFT.p(np.pi/4, qr[0])
qcQFT.barrier(qr)
qcQFT.cx(qr[1], qr[0])
qcQFT.barrier(qr)
qcQFT.p(-np.pi/4, qr[0])
qcQFT.barrier(qr)
qcQFT.cx(qr[1], qr[0])
qcQFT.barrier(qr)
qcQFT.p(np.pi/8, qr[0])
qcQFT.barrier(qr)
qcQFT.cx(qr[2], qr[0])
qcQFT.barrier(qr)
qcQFT.p(-np.pi/8, qr[0])
qcQFT.barrier(qr)
qcQFT.cx(qr[2], qr[0])
qcQFT.barrier(qr)
qcQFT.p(0.19634954084936207, qr[0])
qcQFT.barrier(qr)
qcQFT.cx(qr[3], qr[0])
qcQFT.barrier(qr)
qcQFT.p(-0.19634954084936207, qr[0])
qcQFT.barrier(qr)
qcQFT.cx(qr[3], qr[0])
qcQFT.barrier(qr)
qcQFT.h(qr[1])
qcQFT.barrier(qr)
qcQFT.p(np.pi/4, qr[1])
qcQFT.barrier(qr)
qcQFT.cx(qr[2], qr[1])
qcQFT.barrier(qr)
qcQFT.p(-np.pi/4, qr[1])
qcQFT.barrier(qr)
qcQFT.cx(qr[2], qr[1])
qcQFT.barrier(qr)
qcQFT.p(np.pi/8, qr[1])
qcQFT.barrier(qr)
qcQFT.cx(qr[3], qr[1])
qcQFT.barrier(qr)
qcQFT.p(-np.pi/8, qr[1])
qcQFT.barrier(qr)
qcQFT.cx(qr[3], qr[1])
qcQFT.barrier(qr)
qcQFT.h(qr[2])
qcQFT.barrier(qr)
qcQFT.p(np.pi/4, qr[2])
qcQFT.barrier(qr)
qcQFT.cx(qr[3], qr[2])
qcQFT.barrier(qr)
qcQFT.p(-np.pi/4, qr[2])
qcQFT.barrier(qr)
qcQFT.cx(qr[3], qr[2])
qcQFT.barrier(qr)
qcQFT.h(qr[3])
qcQFT.barrier(qr)

print(qcQFT)