import numpy as np
from qiskit import QuantumCircuit
from qiskit import QuantumRegister
qr = QuantumRegister(4)
qc = QuantumCircuit(qr)

qc.p(np.pi/2, qr[0])
qc.barrier(qr)
qc.h(qr[0])
qc.barrier(qr)
qc.p(-np.pi/4, qr[0])
qc.barrier(qr)
qc.h(qr[0])
qc.barrier(qr)
qc.p(-np.pi/2, qr[0])
qc.barrier(qr)
qc.cx(qr[1], qr[0])
qc.barrier(qr)
qc.p(np.pi/2, qr[0])
qc.barrier(qr)
qc.h(qr[0])
qc.barrier(qr)
qc.p(np.pi/4, qr[0])
qc.barrier(qr)
qc.h(qr[0])
qc.barrier(qr)
qc.p(-np.pi/2, qr[0])
qc.barrier(qr)
qc.p(np.pi/8, qr[0])
qc.barrier(qr)
qc.cx(qr[1], qr[0])
qc.barrier(qr)
qc.p(-np.pi/8, qr[0])
qc.barrier(qr)
qc.cx(qr[1], qr[0])
qc.barrier(qr)
qc.h(qr[0])
qc.barrier(qr)
qc.cx(qr[3], qr[0])
qc.barrier(qr)
qc.p(-np.pi/4, qr[0])
qc.barrier(qr)
qc.cx(qr[1], qr[0])
qc.barrier(qr)
qc.p(np.pi/4, qr[0])
qc.barrier(qr)
qc.cx(qr[3], qr[0])
qc.barrier(qr)
qc.p(-np.pi/4, qr[0])
qc.barrier(qr)
qc.cx(qr[1], qr[0])
qc.barrier(qr)
qc.p(np.pi/4, qr[0])
qc.barrier(qr)
qc.h(qr[0])
qc.barrier(qr)
qc.p(np.pi/4, qr[3])
qc.barrier(qr)
qc.cx(qr[1], qr[3])
qc.barrier(qr)
qc.p(-np.pi/4, qr[3])
qc.barrier(qr)
qc.p(np.pi/4, qr[1])
qc.barrier(qr)
qc.cx(qr[1], qr[3])
qc.barrier(qr)
qc.p(-np.pi/8, qr[0])
qc.barrier(qr)
qc.cx(qr[1], qr[0])
qc.barrier(qr)
qc.p(np.pi/8, qr[0])
qc.barrier(qr)
qc.cx(qr[1], qr[0])
qc.barrier(qr)
qc.h(qr[0])
qc.barrier(qr)
qc.cx(qr[3], qr[0])
qc.barrier(qr)
qc.p(-np.pi/4, qr[0])
qc.barrier(qr)
qc.cx(qr[1], qr[0])
qc.barrier(qr)
qc.p(np.pi/4, qr[0])
qc.barrier(qr)
qc.cx(qr[3], qr[0])
qc.barrier(qr)
qc.p(-np.pi/4, qr[0])
qc.barrier(qr)
qc.cx(qr[1], qr[0])
qc.barrier(qr)
qc.p(np.pi/4, qr[0])
qc.barrier(qr)
qc.h(qr[0])
qc.barrier(qr)
qc.p(np.pi/4, qr[3])
qc.barrier(qr)
qc.cx(qr[1], qr[3])
qc.barrier(qr)
qc.p(-np.pi/4, qr[3])
qc.barrier(qr)
qc.p(np.pi/4, qr[1])
qc.barrier(qr)
qc.cx(qr[1], qr[3])
qc.barrier(qr)
qc.p(0.19634954084936207, qr[2])
qc.barrier(qr)
qc.cx(qr[1], qr[2])
qc.barrier(qr)
qc.p(-0.19634954084936207, qr[2])
qc.barrier(qr)
qc.cx(qr[1], qr[2])
qc.barrier(qr)
qc.h(qr[2])
qc.barrier(qr)
qc.cx(qr[0], qr[2])
qc.barrier(qr)
qc.p(-np.pi/4, qr[2])
qc.barrier(qr)
qc.cx(qr[1], qr[2])
qc.barrier(qr)
qc.p(np.pi/4, qr[2])
qc.barrier(qr)
qc.cx(qr[0], qr[2])
qc.barrier(qr)
qc.p(-np.pi/4, qr[2])
qc.barrier(qr)
qc.cx(qr[1], qr[2])
qc.barrier(qr)
qc.p(np.pi/4, qr[2])
qc.barrier(qr)
qc.h(qr[2])
qc.barrier(qr)
qc.p(np.pi/4, qr[0])
qc.barrier(qr)
qc.cx(qr[1], qr[0])
qc.barrier(qr)
qc.p(-np.pi/4, qr[0])
qc.barrier(qr)
qc.p(np.pi/4, qr[1])
qc.barrier(qr)
qc.cx(qr[1], qr[0])
qc.barrier(qr)
qc.p(-0.19634954084936207, qr[2])
qc.barrier(qr)
qc.cx(qr[1], qr[2])
qc.barrier(qr)
qc.p(0.19634954084936207, qr[2])
qc.barrier(qr)
qc.cx(qr[1], qr[2])
qc.barrier(qr)
qc.h(qr[2])
qc.barrier(qr)
qc.cx(qr[0], qr[2])
qc.barrier(qr)
qc.p(-np.pi/4, qr[2])
qc.barrier(qr)
qc.cx(qr[1], qr[2])
qc.barrier(qr)
qc.p(np.pi/4, qr[2])
qc.barrier(qr)
qc.cx(qr[0], qr[2])
qc.barrier(qr)
qc.p(-np.pi/4, qr[2])
qc.barrier(qr)
qc.cx(qr[1], qr[2])
qc.barrier(qr)
qc.p(np.pi/4, qr[2])
qc.barrier(qr)
qc.h(qr[2])
qc.barrier(qr)
qc.p(np.pi/4, qr[0])
qc.barrier(qr)
qc.cx(qr[1], qr[0])
qc.barrier(qr)
qc.p(-np.pi/4, qr[0])
qc.barrier(qr)
qc.p(np.pi/4, qr[1])
qc.barrier(qr)
qc.cx(qr[1], qr[0])
qc.barrier(qr)
qc.p(np.pi/2, qr[3])
qc.barrier(qr)
qc.h(qr[3])
qc.barrier(qr)
qc.p(-np.pi/4, qr[3])
qc.barrier(qr)
qc.h(qr[3])
qc.barrier(qr)
qc.p(-np.pi/2, qr[3])
qc.barrier(qr)
qc.cx(qr[1], qr[3])
qc.barrier(qr)
qc.p(np.pi/2, qr[3])
qc.barrier(qr)
qc.h(qr[3])
qc.barrier(qr)
qc.p(np.pi/4, qr[3])
qc.barrier(qr)
qc.h(qr[3])
qc.barrier(qr)
qc.p(-np.pi/2, qr[3])
qc.barrier(qr)
qc.p(np.pi/8, qr[2])
qc.barrier(qr)
qc.cx(qr[1], qr[2])
qc.barrier(qr)
qc.p(-np.pi/8, qr[2])
qc.barrier(qr)
qc.cx(qr[1], qr[2])
qc.barrier(qr)
qc.h(qr[2])
qc.barrier(qr)
qc.cx(qr[0], qr[2])
qc.barrier(qr)
qc.p(-np.pi/4, qr[2])
qc.barrier(qr)
qc.cx(qr[1], qr[2])
qc.barrier(qr)
qc.p(np.pi/4, qr[2])
qc.barrier(qr)
qc.cx(qr[0], qr[2])
qc.barrier(qr)
qc.p(-np.pi/4, qr[2])
qc.barrier(qr)
qc.cx(qr[1], qr[2])
qc.barrier(qr)
qc.p(np.pi/4, qr[2])
qc.barrier(qr)
qc.h(qr[2])
qc.barrier(qr)
qc.p(np.pi/4, qr[0])
qc.barrier(qr)
qc.cx(qr[1], qr[0])
qc.barrier(qr)
qc.p(-np.pi/4, qr[0])
qc.barrier(qr)
qc.p(np.pi/4, qr[1])
qc.barrier(qr)
qc.cx(qr[1], qr[0])
qc.barrier(qr)
qc.p(-np.pi/8, qr[2])
qc.barrier(qr)
qc.cx(qr[1], qr[2])
qc.barrier(qr)
qc.p(np.pi/8, qr[2])
qc.barrier(qr)
qc.cx(qr[1], qr[2])
qc.barrier(qr)
qc.h(qr[2])
qc.barrier(qr)
qc.cx(qr[0], qr[2])
qc.barrier(qr)
qc.p(-np.pi/4, qr[2])
qc.barrier(qr)
qc.cx(qr[1], qr[2])
qc.barrier(qr)
qc.p(np.pi/4, qr[2])
qc.barrier(qr)
qc.cx(qr[0], qr[2])
qc.barrier(qr)
qc.p(-np.pi/4, qr[2])
qc.barrier(qr)
qc.cx(qr[1], qr[2])
qc.barrier(qr)
qc.p(np.pi/4, qr[2])
qc.barrier(qr)
qc.h(qr[2])
qc.barrier(qr)
qc.p(np.pi/4, qr[0])
qc.barrier(qr)
qc.cx(qr[1], qr[0])
qc.barrier(qr)
qc.p(-np.pi/4, qr[0])
qc.barrier(qr)
qc.p(np.pi/4, qr[1])
qc.barrier(qr)
qc.cx(qr[1], qr[0])
qc.barrier(qr)
qc.p(np.pi/2, qr[0])
qc.barrier(qr)
qc.h(qr[0])
qc.barrier(qr)
qc.p(-np.pi/4, qr[0])
qc.barrier(qr)
qc.h(qr[0])
qc.barrier(qr)
qc.p(-np.pi/2, qr[0])
qc.barrier(qr)
qc.cx(qr[1], qr[0])
qc.barrier(qr)
qc.p(np.pi/2, qr[0])
qc.barrier(qr)
qc.h(qr[0])
qc.barrier(qr)
qc.p(np.pi/4, qr[0])
qc.barrier(qr)
qc.h(qr[0])
qc.barrier(qr)
qc.p(-np.pi/2, qr[0])
qc.barrier(qr)

print(qc)

qc.draw(output="mpl", plot_barriers=False, filename="qftControlMixedAbs.png")