import numpy as np
from qiskit import QuantumCircuit
from qiskit import QuantumRegister
qr = QuantumRegister(3)
qc = QuantumCircuit(qr)

qc.h(qr[2])
qc.barrier(qr)
qc.p(np.pi/4, qr[2])
qc.barrier(qr)
qc.cx(qr[1], qr[2])
qc.barrier(qr)
qc.p(-np.pi/4, qr[2])
qc.barrier(qr)
qc.cx(qr[1], qr[2])
qc.barrier(qr)
qc.p(np.pi/8, qr[2])
qc.barrier(qr)
qc.cx(qr[0], qr[2])
qc.barrier(qr)
qc.p(-np.pi/8, qr[2])
qc.barrier(qr)
qc.cx(qr[0], qr[2])
qc.barrier(qr)
qc.h(qr[1])
qc.barrier(qr)
qc.p(np.pi/4, qr[1])
qc.barrier(qr)
qc.cx(qr[0], qr[1])
qc.barrier(qr)
qc.p(-np.pi/4, qr[1])
qc.barrier(qr)
qc.cx(qr[0], qr[1])
qc.barrier(qr)
qc.h(qr[0])
qc.barrier(qr)

print(qc)