import numpy as np
from qiskit import QuantumCircuit
from qiskit import QuantumRegister
qr = QuantumRegister(8)
qc = QuantumCircuit(qr)

qc.h(qr[7])
qc.barrier(qr)
qc.cx(qr[7], qr[6])
qc.barrier(qr)
qc.p(np.pi/4, qr[6])
qc.barrier(qr)
qc.cx(qr[7], qr[6])
qc.barrier(qr)
qc.p(-np.pi/4, qr[6])
qc.barrier(qr)
qc.h(qr[6])
qc.barrier(qr)
qc.cx(qr[7], qr[5])
qc.barrier(qr)
qc.p(np.pi/8, qr[5])
qc.barrier(qr)
qc.cx(qr[7], qr[5])
qc.barrier(qr)
qc.p(-np.pi/8, qr[5])
qc.barrier(qr)
qc.cx(qr[6], qr[5])
qc.barrier(qr)
qc.p(np.pi/4, qr[5])
qc.barrier(qr)
qc.cx(qr[6], qr[5])
qc.barrier(qr)
qc.p(-np.pi/4, qr[5])
qc.barrier(qr)
qc.h(qr[5])
qc.barrier(qr)
qc.p(np.pi/2, qr[6])
qc.barrier(qr)
qc.h(qr[6])
qc.barrier(qr)
qc.p(-np.pi/4, qr[6])
qc.barrier(qr)
qc.h(qr[6])
qc.barrier(qr)
qc.p(-np.pi/2, qr[6])
qc.barrier(qr)
qc.cx(qr[1], qr[6])
qc.barrier(qr)
qc.p(np.pi/2, qr[6])
qc.barrier(qr)
qc.h(qr[6])
qc.barrier(qr)
qc.p(np.pi/4, qr[6])
qc.barrier(qr)
qc.h(qr[6])
qc.barrier(qr)
qc.p(-np.pi/2, qr[6])
qc.barrier(qr)
qc.p(np.pi/8, qr[6])
qc.barrier(qr)
qc.cx(qr[1], qr[6])
qc.barrier(qr)
qc.p(-np.pi/8, qr[6])
qc.barrier(qr)
qc.cx(qr[1], qr[6])
qc.barrier(qr)
qc.h(qr[6])
qc.barrier(qr)
qc.cx(qr[7], qr[6])
qc.barrier(qr)
qc.p(-np.pi/4, qr[6])
qc.barrier(qr)
qc.cx(qr[1], qr[6])
qc.barrier(qr)
qc.p(np.pi/4, qr[6])
qc.barrier(qr)
qc.cx(qr[7], qr[6])
qc.barrier(qr)
qc.p(-np.pi/4, qr[6])
qc.barrier(qr)
qc.cx(qr[1], qr[6])
qc.barrier(qr)
qc.p(np.pi/4, qr[6])
qc.barrier(qr)
qc.h(qr[6])
qc.barrier(qr)
qc.p(np.pi/4, qr[7])
qc.barrier(qr)
qc.cx(qr[1], qr[7])
qc.barrier(qr)
qc.p(-np.pi/4, qr[7])
qc.barrier(qr)
qc.p(np.pi/4, qr[1])
qc.barrier(qr)
qc.cx(qr[1], qr[7])
qc.barrier(qr)
qc.p(-np.pi/8, qr[6])
qc.barrier(qr)
qc.cx(qr[1], qr[6])
qc.barrier(qr)
qc.p(np.pi/8, qr[6])
qc.barrier(qr)
qc.cx(qr[1], qr[6])
qc.barrier(qr)
qc.h(qr[6])
qc.barrier(qr)
qc.cx(qr[7], qr[6])
qc.barrier(qr)
qc.p(-np.pi/4, qr[6])
qc.barrier(qr)
qc.cx(qr[1], qr[6])
qc.barrier(qr)
qc.p(np.pi/4, qr[6])
qc.barrier(qr)
qc.cx(qr[7], qr[6])
qc.barrier(qr)
qc.p(-np.pi/4, qr[6])
qc.barrier(qr)
qc.cx(qr[1], qr[6])
qc.barrier(qr)
qc.p(np.pi/4, qr[6])
qc.barrier(qr)
qc.h(qr[6])
qc.barrier(qr)
qc.p(np.pi/4, qr[7])
qc.barrier(qr)
qc.cx(qr[1], qr[7])
qc.barrier(qr)
qc.p(-np.pi/4, qr[7])
qc.barrier(qr)
qc.p(np.pi/4, qr[1])
qc.barrier(qr)
qc.cx(qr[1], qr[7])
qc.barrier(qr)
qc.p(np.pi/2, qr[7])
qc.barrier(qr)
qc.h(qr[7])
qc.barrier(qr)
qc.p(-np.pi/4, qr[7])
qc.barrier(qr)
qc.h(qr[7])
qc.barrier(qr)
qc.p(-np.pi/2, qr[7])
qc.barrier(qr)
qc.cx(qr[1], qr[7])
qc.barrier(qr)
qc.p(np.pi/2, qr[7])
qc.barrier(qr)
qc.h(qr[7])
qc.barrier(qr)
qc.p(np.pi/4, qr[7])
qc.barrier(qr)
qc.h(qr[7])
qc.barrier(qr)
qc.p(-np.pi/2, qr[7])
qc.barrier(qr)
qc.p(np.pi/4, qr[6])
qc.barrier(qr)
qc.cx(qr[1], qr[6])
qc.barrier(qr)
qc.p(-np.pi/4, qr[6])
qc.barrier(qr)
qc.cx(qr[1], qr[6])
qc.barrier(qr)
qc.h(qr[6])
qc.barrier(qr)
qc.cx(qr[4], qr[6])
qc.barrier(qr)
qc.p(-np.pi/4, qr[6])
qc.barrier(qr)
qc.cx(qr[1], qr[6])
qc.barrier(qr)
qc.p(np.pi/4, qr[6])
qc.barrier(qr)
qc.cx(qr[4], qr[6])
qc.barrier(qr)
qc.p(-np.pi/4, qr[6])
qc.barrier(qr)
qc.cx(qr[1], qr[6])
qc.barrier(qr)
qc.p(np.pi/4, qr[6])
qc.barrier(qr)
qc.h(qr[6])
qc.barrier(qr)
qc.p(np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[1], qr[4])
qc.barrier(qr)
qc.p(-np.pi/4, qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[1])
qc.barrier(qr)
qc.cx(qr[1], qr[4])
qc.barrier(qr)
qc.p(-np.pi/4, qr[6])
qc.barrier(qr)
qc.cx(qr[1], qr[6])
qc.barrier(qr)
qc.p(np.pi/4, qr[6])
qc.barrier(qr)
qc.cx(qr[1], qr[6])
qc.barrier(qr)
qc.h(qr[6])
qc.barrier(qr)
qc.cx(qr[4], qr[6])
qc.barrier(qr)
qc.p(-np.pi/4, qr[6])
qc.barrier(qr)
qc.cx(qr[1], qr[6])
qc.barrier(qr)
qc.p(np.pi/4, qr[6])
qc.barrier(qr)
qc.cx(qr[4], qr[6])
qc.barrier(qr)
qc.p(-np.pi/4, qr[6])
qc.barrier(qr)
qc.cx(qr[1], qr[6])
qc.barrier(qr)
qc.p(np.pi/4, qr[6])
qc.barrier(qr)
qc.h(qr[6])
qc.barrier(qr)
qc.p(np.pi/4, qr[4])
qc.barrier(qr)
qc.cx(qr[1], qr[4])
qc.barrier(qr)
qc.p(-np.pi/4, qr[4])
qc.barrier(qr)
qc.p(np.pi/4, qr[1])
qc.barrier(qr)
qc.cx(qr[1], qr[4])
qc.barrier(qr)
qc.p(np.pi/8, qr[6])
qc.barrier(qr)
qc.cx(qr[1], qr[6])
qc.barrier(qr)
qc.p(-np.pi/8, qr[6])
qc.barrier(qr)
qc.cx(qr[1], qr[6])
qc.barrier(qr)
qc.h(qr[6])
qc.barrier(qr)
qc.cx(qr[5], qr[6])
qc.barrier(qr)
qc.p(-np.pi/4, qr[6])
qc.barrier(qr)
qc.cx(qr[1], qr[6])
qc.barrier(qr)
qc.p(np.pi/4, qr[6])
qc.barrier(qr)
qc.cx(qr[5], qr[6])
qc.barrier(qr)
qc.p(-np.pi/4, qr[6])
qc.barrier(qr)
qc.cx(qr[1], qr[6])
qc.barrier(qr)
qc.p(np.pi/4, qr[6])
qc.barrier(qr)
qc.h(qr[6])
qc.barrier(qr)
qc.p(np.pi/4, qr[5])
qc.barrier(qr)
qc.cx(qr[1], qr[5])
qc.barrier(qr)
qc.p(-np.pi/4, qr[5])
qc.barrier(qr)
qc.p(np.pi/4, qr[1])
qc.barrier(qr)
qc.cx(qr[1], qr[5])
qc.barrier(qr)
qc.p(-np.pi/8, qr[6])
qc.barrier(qr)
qc.cx(qr[1], qr[6])
qc.barrier(qr)
qc.p(np.pi/8, qr[6])
qc.barrier(qr)
qc.cx(qr[1], qr[6])
qc.barrier(qr)
qc.h(qr[6])
qc.barrier(qr)
qc.cx(qr[5], qr[6])
qc.barrier(qr)
qc.p(-np.pi/4, qr[6])
qc.barrier(qr)
qc.cx(qr[1], qr[6])
qc.barrier(qr)
qc.p(np.pi/4, qr[6])
qc.barrier(qr)
qc.cx(qr[5], qr[6])
qc.barrier(qr)
qc.p(-np.pi/4, qr[6])
qc.barrier(qr)
qc.cx(qr[1], qr[6])
qc.barrier(qr)
qc.p(np.pi/4, qr[6])
qc.barrier(qr)
qc.h(qr[6])
qc.barrier(qr)
qc.p(np.pi/4, qr[5])
qc.barrier(qr)
qc.cx(qr[1], qr[5])
qc.barrier(qr)
qc.p(-np.pi/4, qr[5])
qc.barrier(qr)
qc.p(np.pi/4, qr[1])
qc.barrier(qr)
qc.cx(qr[1], qr[5])
qc.barrier(qr)
qc.p(np.pi/4, qr[7])
qc.barrier(qr)
qc.cx(qr[1], qr[7])
qc.barrier(qr)
qc.p(-np.pi/4, qr[7])
qc.barrier(qr)
qc.cx(qr[1], qr[7])
qc.barrier(qr)
qc.h(qr[7])
qc.barrier(qr)
qc.cx(qr[5], qr[7])
qc.barrier(qr)
qc.p(-np.pi/4, qr[7])
qc.barrier(qr)
qc.cx(qr[1], qr[7])
qc.barrier(qr)
qc.p(np.pi/4, qr[7])
qc.barrier(qr)
qc.cx(qr[5], qr[7])
qc.barrier(qr)
qc.p(-np.pi/4, qr[7])
qc.barrier(qr)
qc.cx(qr[1], qr[7])
qc.barrier(qr)
qc.p(np.pi/4, qr[7])
qc.barrier(qr)
qc.h(qr[7])
qc.barrier(qr)
qc.p(np.pi/4, qr[5])
qc.barrier(qr)
qc.cx(qr[1], qr[5])
qc.barrier(qr)
qc.p(-np.pi/4, qr[5])
qc.barrier(qr)
qc.p(np.pi/4, qr[1])
qc.barrier(qr)
qc.cx(qr[1], qr[5])
qc.barrier(qr)
qc.p(-np.pi/4, qr[7])
qc.barrier(qr)
qc.cx(qr[1], qr[7])
qc.barrier(qr)
qc.p(np.pi/4, qr[7])
qc.barrier(qr)
qc.cx(qr[1], qr[7])
qc.barrier(qr)
qc.h(qr[7])
qc.barrier(qr)
qc.cx(qr[5], qr[7])
qc.barrier(qr)
qc.p(-np.pi/4, qr[7])
qc.barrier(qr)
qc.cx(qr[1], qr[7])
qc.barrier(qr)
qc.p(np.pi/4, qr[7])
qc.barrier(qr)
qc.cx(qr[5], qr[7])
qc.barrier(qr)
qc.p(-np.pi/4, qr[7])
qc.barrier(qr)
qc.cx(qr[1], qr[7])
qc.barrier(qr)
qc.p(np.pi/4, qr[7])
qc.barrier(qr)
qc.h(qr[7])
qc.barrier(qr)
qc.p(np.pi/4, qr[5])
qc.barrier(qr)
qc.cx(qr[1], qr[5])
qc.barrier(qr)
qc.p(-np.pi/4, qr[5])
qc.barrier(qr)
qc.p(np.pi/4, qr[1])
qc.barrier(qr)
qc.cx(qr[1], qr[5])
qc.barrier(qr)
qc.p(np.pi/2, qr[7])
qc.barrier(qr)
qc.h(qr[7])
qc.barrier(qr)
qc.p(-np.pi/4, qr[7])
qc.barrier(qr)
qc.h(qr[7])
qc.barrier(qr)
qc.p(-np.pi/2, qr[7])
qc.barrier(qr)
qc.cx(qr[1], qr[7])
qc.barrier(qr)
qc.p(np.pi/2, qr[7])
qc.barrier(qr)
qc.h(qr[7])
qc.barrier(qr)
qc.p(np.pi/4, qr[7])
qc.barrier(qr)
qc.h(qr[7])
qc.barrier(qr)
qc.p(-np.pi/2, qr[7])
qc.barrier(qr)
qc.h(qr[6])
qc.barrier(qr)
qc.cx(qr[7], qr[6])
qc.barrier(qr)
qc.p(-np.pi/4, qr[6])
qc.barrier(qr)
qc.cx(qr[1], qr[6])
qc.barrier(qr)
qc.p(np.pi/4, qr[6])
qc.barrier(qr)
qc.cx(qr[7], qr[6])
qc.barrier(qr)
qc.p(-np.pi/4, qr[6])
qc.barrier(qr)
qc.cx(qr[1], qr[6])
qc.barrier(qr)
qc.p(np.pi/4, qr[6])
qc.barrier(qr)
qc.h(qr[6])
qc.barrier(qr)
qc.p(np.pi/4, qr[7])
qc.barrier(qr)
qc.cx(qr[1], qr[7])
qc.barrier(qr)
qc.p(-np.pi/4, qr[7])
qc.barrier(qr)
qc.p(np.pi/4, qr[1])
qc.barrier(qr)
qc.cx(qr[1], qr[7])
qc.barrier(qr)
qc.p(np.pi/8, qr[6])
qc.barrier(qr)
qc.cx(qr[1], qr[6])
qc.barrier(qr)
qc.p(-np.pi/8, qr[6])
qc.barrier(qr)
qc.cx(qr[1], qr[6])
qc.barrier(qr)
qc.h(qr[6])
qc.barrier(qr)
qc.cx(qr[7], qr[6])
qc.barrier(qr)
qc.p(-np.pi/4, qr[6])
qc.barrier(qr)
qc.cx(qr[1], qr[6])
qc.barrier(qr)
qc.p(np.pi/4, qr[6])
qc.barrier(qr)
qc.cx(qr[7], qr[6])
qc.barrier(qr)
qc.p(-np.pi/4, qr[6])
qc.barrier(qr)
qc.cx(qr[1], qr[6])
qc.barrier(qr)
qc.p(np.pi/4, qr[6])
qc.barrier(qr)
qc.h(qr[6])
qc.barrier(qr)
qc.p(np.pi/4, qr[7])
qc.barrier(qr)
qc.cx(qr[1], qr[7])
qc.barrier(qr)
qc.p(-np.pi/4, qr[7])
qc.barrier(qr)
qc.p(np.pi/4, qr[1])
qc.barrier(qr)
qc.cx(qr[1], qr[7])
qc.barrier(qr)
qc.p(-np.pi/8, qr[6])
qc.barrier(qr)
qc.cx(qr[1], qr[6])
qc.barrier(qr)
qc.p(np.pi/8, qr[6])
qc.barrier(qr)
qc.cx(qr[1], qr[6])
qc.barrier(qr)
qc.p(np.pi/2, qr[6])
qc.barrier(qr)
qc.h(qr[6])
qc.barrier(qr)
qc.p(-np.pi/4, qr[6])
qc.barrier(qr)
qc.h(qr[6])
qc.barrier(qr)
qc.p(-np.pi/2, qr[6])
qc.barrier(qr)
qc.cx(qr[1], qr[6])
qc.barrier(qr)
qc.p(np.pi/2, qr[6])
qc.barrier(qr)
qc.h(qr[6])
qc.barrier(qr)
qc.p(np.pi/4, qr[6])
qc.barrier(qr)
qc.h(qr[6])
qc.barrier(qr)
qc.p(-np.pi/2, qr[6])
qc.barrier(qr)
qc.h(qr[5])
qc.barrier(qr)
qc.p(np.pi/4, qr[5])
qc.barrier(qr)
qc.cx(qr[6], qr[5])
qc.barrier(qr)
qc.p(-np.pi/4, qr[5])
qc.barrier(qr)
qc.cx(qr[6], qr[5])
qc.barrier(qr)
qc.p(np.pi/8, qr[5])
qc.barrier(qr)
qc.cx(qr[7], qr[5])
qc.barrier(qr)
qc.p(-np.pi/8, qr[5])
qc.barrier(qr)
qc.cx(qr[7], qr[5])
qc.barrier(qr)
qc.h(qr[6])
qc.barrier(qr)
qc.p(np.pi/4, qr[6])
qc.barrier(qr)
qc.cx(qr[7], qr[6])
qc.barrier(qr)
qc.p(-np.pi/4, qr[6])
qc.barrier(qr)
qc.cx(qr[7], qr[6])
qc.barrier(qr)
qc.h(qr[7])
qc.barrier(qr)

print(qc)

qc.draw(output="mpl", plot_barriers=False, filename="circuitCS-mpl.png")